# AÑADIR COLUMNA MARCA Y TALLA EN LA TABLA ZAPATILLA
ALTER table zapatilla
ADD COLUMN
marca VARCHAR (45) NOT NULL;
ALTER table zapatilla
ADD COLUMN
talla INT NOT NULL;
# ALTERAR TIPO DE DATO EN LA COLUMNA SALARIO DE LA TABLA EMPLEADOS
ALTER table empleados
MODIFY COLUMN
salario FLOAT;
# ELIMINAR LA COLUMNA PAIS DE LA TABLA CLIENTES
ALTER table clientes
DROP COLUMN pais;
# MODIFICAR COLUMNA CODIGO_POSTAL A INTEGER DE 5 CARACTERES EN LA TABLA CLIENTES
ALTER table clientes
MODIFY COLUMN codigo_postal INT (5);
# INCLUIR COLUMNA EN LA TABLA FACTURAS
ALTER table facturas
ADD COLUMN total FLOAT;